import { forwardRef } from 'react'
import ReactMarkdown from 'react-markdown'

interface PdfTemplateProps {
	imageUrl: string | null
	chatHistory: { role: 'user' | 'assistant'; content: string }[]
	t: any
}

export const PdfTemplate = forwardRef<HTMLDivElement, PdfTemplateProps>(
	({ imageUrl, chatHistory, t }, ref) => {
		return (
			<div
				ref={ref}
				className='fixed top-0 left-0 -z-50 bg-white text-black p-8 font-sans'
				style={{ width: '210mm', minHeight: '297mm' }}>
				{/* Header */}
				<div className='flex items-center justify-between border-b-2 border-black pb-4 mb-8'>
					<div className='flex items-center gap-4'>
						{/* Assuming logo is available publicly */}
						<img src='/logo.svg' alt='Dakila Logo' className='w-12 h-12' />
						<div>
							<h1 className='text-2xl font-bold uppercase tracking-widest'>
								Dakila Research
							</h1>
							<p className='text-xs font-mono uppercase tracking-widest text-gray-600'>
								{t.headerTitle}
							</p>
						</div>
					</div>
					<div className='text-right'>
						<p className='text-sm font-mono text-gray-500'>
							DATE: {new Date().toLocaleDateString()}
						</p>
						<p className='text-sm font-mono text-gray-500'>
							CONFIDENTIAL REPORT
						</p>
					</div>
				</div>

				{/* Image Analysis Section */}
				{imageUrl && (
					<div className='mb-8 border border-gray-200 rounded-lg p-4 bg-gray-50 break-inside-avoid'>
						<h2 className='text-sm font-bold uppercase tracking-widest mb-4 border-l-4 border-black pl-2'>
							Analyzed Subject
						</h2>
						<div className='flex justify-center'>
							<img
								src={imageUrl}
								alt='Analyzed Subject'
								className='max-h-[300px] object-contain rounded border border-gray-300'
							/>
						</div>
					</div>
				)}

				{/* Analysis Results / Chat History */}
				<div className='space-y-6'>
					<h2 className='text-sm font-bold uppercase tracking-widest mb-4 border-l-4 border-black pl-2'>
						Analysis Report
					</h2>

					{chatHistory.map((msg, index) => (
						<div
							key={index}
							className={`p-4 rounded-lg text-sm leading-relaxed ${
								msg.role === 'user'
									? 'bg-gray-100 border-l-2 border-gray-400 italic text-gray-700'
									: 'bg-white border border-gray-200 text-gray-900'
							}`}>
							<strong className='block text-xs font-mono text-gray-500 mb-2 uppercase'>
								{msg.role === 'user' ? 'Query' : 'System Response'}
							</strong>
							<div className='prose prose-sm max-w-none prose-p:my-1 prose-headings:my-2'>
								{msg.role === 'assistant' ? (
									<ReactMarkdown>{msg.content}</ReactMarkdown>
								) : (
									msg.content
								)}
							</div>
						</div>
					))}
				</div>

				{/* Footer */}
				<div className='fixed bottom-8 left-8 right-8 text-center border-t border-gray-200 pt-4'>
					<p className='text-[10px] font-mono text-gray-400'>
						GENERATED BY DAKILA SYMBOLOGY & FREQUENCY ANALYZER AI
					</p>
				</div>
			</div>
		)
	}
)

PdfTemplate.displayName = 'PdfTemplate'
